<?php

namespace ContainerDDvqPPK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qh_2eJGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qh.2eJG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiProductController::list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::list()', 'getApiProductControllerlistService', true],
            'App\\Controller\\ApiProductController::show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ApiProductController::show()', 'getApiProductControllershowService', true],
            'App\\Controller\\ApiProductController::create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::create()', 'getApiProductControllercreateService', true],
            'App\\Controller\\ApiProductController::update' => ['privates', '.service_locator.0I04bAC.App\\Controller\\ApiProductController::update()', 'getApiProductControllerupdateService', true],
            'App\\Controller\\ApiProductController::delete' => ['privates', '.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()', 'getApiProductControllerdeleteService', true],
            'App\\Controller\\ApiUserController::list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiUserController::list()', 'getApiUserControllerlistService', true],
            'App\\Controller\\ApiUserController::show' => ['privates', '.service_locator.kYAceIU.App\\Controller\\ApiUserController::show()', 'getApiUserControllershowService', true],
            'App\\Controller\\ApiUserController::create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\ApiUserController::create()', 'getApiUserControllercreateService', true],
            'App\\Controller\\ApiUserController::update' => ['privates', '.service_locator.3P8Qjmz.App\\Controller\\ApiUserController::update()', 'getApiUserControllerupdateService', true],
            'App\\Controller\\ApiUserController::delete' => ['privates', '.service_locator.q.9q_tU.App\\Controller\\ApiUserController::delete()', 'getApiUserControllerdeleteService', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.dcfjolD.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\ApiProductController:list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::list()', 'getApiProductControllerlistService', true],
            'App\\Controller\\ApiProductController:show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ApiProductController::show()', 'getApiProductControllershowService', true],
            'App\\Controller\\ApiProductController:create' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiProductController::create()', 'getApiProductControllercreateService', true],
            'App\\Controller\\ApiProductController:update' => ['privates', '.service_locator.0I04bAC.App\\Controller\\ApiProductController::update()', 'getApiProductControllerupdateService', true],
            'App\\Controller\\ApiProductController:delete' => ['privates', '.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()', 'getApiProductControllerdeleteService', true],
            'App\\Controller\\ApiUserController:list' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\ApiUserController::list()', 'getApiUserControllerlistService', true],
            'App\\Controller\\ApiUserController:show' => ['privates', '.service_locator.kYAceIU.App\\Controller\\ApiUserController::show()', 'getApiUserControllershowService', true],
            'App\\Controller\\ApiUserController:create' => ['privates', '.service_locator.O6aUYCb.App\\Controller\\ApiUserController::create()', 'getApiUserControllercreateService', true],
            'App\\Controller\\ApiUserController:update' => ['privates', '.service_locator.3P8Qjmz.App\\Controller\\ApiUserController::update()', 'getApiUserControllerupdateService', true],
            'App\\Controller\\ApiUserController:delete' => ['privates', '.service_locator.q.9q_tU.App\\Controller\\ApiUserController::delete()', 'getApiUserControllerdeleteService', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.dcfjolD.App\\Controller\\ProductController::index()', 'getProductControllerindexService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.3BoFVFw.App\\Controller\\ProductController::new()', 'getProductControllernewService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.qHOVbN9.App\\Controller\\ProductController::show()', 'getProductControllershowService', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::edit()', 'getProductControllereditService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.FmlJA_f.App\\Controller\\ProductController::delete()', 'getProductControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiProductController::list' => '?',
            'App\\Controller\\ApiProductController::show' => '?',
            'App\\Controller\\ApiProductController::create' => '?',
            'App\\Controller\\ApiProductController::update' => '?',
            'App\\Controller\\ApiProductController::delete' => '?',
            'App\\Controller\\ApiUserController::list' => '?',
            'App\\Controller\\ApiUserController::show' => '?',
            'App\\Controller\\ApiUserController::create' => '?',
            'App\\Controller\\ApiUserController::update' => '?',
            'App\\Controller\\ApiUserController::delete' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiProductController:list' => '?',
            'App\\Controller\\ApiProductController:show' => '?',
            'App\\Controller\\ApiProductController:create' => '?',
            'App\\Controller\\ApiProductController:update' => '?',
            'App\\Controller\\ApiProductController:delete' => '?',
            'App\\Controller\\ApiUserController:list' => '?',
            'App\\Controller\\ApiUserController:show' => '?',
            'App\\Controller\\ApiUserController:create' => '?',
            'App\\Controller\\ApiUserController:update' => '?',
            'App\\Controller\\ApiUserController:delete' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
        ]);

        if (isset($container->privates['.service_locator.qh.2eJG'])) {
            return $container->privates['.service_locator.qh.2eJG'];
        }

        return $container->privates['.service_locator.qh.2eJG'] = $instance;
    }
}
