<?php

namespace ContainerDDvqPPK;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0I04bACService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0I04bAC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.0I04bAC.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.0I04bAC": it needs an instance of "App\\Entity\\Product" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'product' => 'App\\Entity\\Product',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.0I04bAC'])) {
            return $container->privates['.service_locator.0I04bAC'];
        }

        return $container->privates['.service_locator.0I04bAC'] = $instance;
    }
}
