<?php

namespace ContainerVGYFD5N;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiProductControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0I04bAC.App\Controller\ApiProductController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0I04bAC'] ?? $container->load('get_ServiceLocator_0I04bACService'));

        if (isset($container->privates['.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()'])) {
            return $container->privates['.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()'];
        }

        $instance = $a->withContext('App\\Controller\\ApiProductController::delete()', $container);

        if (isset($container->privates['.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()'])) {
            return $container->privates['.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()'];
        }

        return $container->privates['.service_locator.0I04bAC.App\\Controller\\ApiProductController::delete()'] = $instance;
    }
}
