<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQMT2Fki\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQMT2Fki/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQMT2Fki.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQMT2Fki\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQMT2Fki\App_KernelDevDebugContainer([
    'container.build_hash' => 'QMT2Fki',
    'container.build_id' => 'd5ab86e4',
    'container.build_time' => 1771236578,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQMT2Fki');
