<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dJA4fY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dJA4fY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1dJA4fY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1dJA4fY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1dJA4fY\App_KernelDevDebugContainer([
    'container.build_hash' => '1dJA4fY',
    'container.build_id' => 'fe480e21',
    'container.build_time' => 1771272177,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dJA4fY');
