<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVGYFD5N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVGYFD5N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVGYFD5N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVGYFD5N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVGYFD5N\App_KernelDevDebugContainer([
    'container.build_hash' => 'VGYFD5N',
    'container.build_id' => '133a03ca',
    'container.build_time' => 1771275722,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVGYFD5N');
