<?php

namespace Container1dJA4fY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiUserControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q.9q_tU.App\Controller\ApiUserController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.q.9q_tU.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.q.9q_tU": it needs an instance of "App\\Entity\\User" but this type has been excluded because it\'s a Doctrine entity.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'user' => 'App\\Entity\\User',
            'em' => '?',
        ]))->withContext('App\\Controller\\ApiUserController::delete()', $container);

        if (isset($container->privates['.service_locator.q.9q_tU.App\\Controller\\ApiUserController::delete()'])) {
            return $container->privates['.service_locator.q.9q_tU.App\\Controller\\ApiUserController::delete()'];
        }

        return $container->privates['.service_locator.q.9q_tU.App\\Controller\\ApiUserController::delete()'] = $instance;
    }
}
